#!/bin/bash

# Extract data using jq and format with awk/sed
name=$(jq -r '.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
formatted_height=$(jq -r '.height/10' data.json)
formatted_weight=$(jq -r '.weight/10' data.json)
type=$(jq -r '.types[0].type.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

# Format the output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall." | \
  sed 's/ Electric/ Electric/'