#!/bin/bash

# Extract raw data
name=$(jq -r '.name' data.json)
height=$(jq -r '.height/10' data.json)
weight=$(jq -r '.weight/10' data.json)
type=$(jq -r '.types[0].type.name' data.json)

# Format with awk
echo "$name $type $weight $height" | awk '{
  name = toupper(substr($1,1,1)) substr($1,2)
  type = toupper(substr($2,1,1)) substr($2,2)
  printf "%s is of type %s, weighs %gkg, and is %gm tall.\n", name, type, $3, $4
}' | sed 's/ $//'